### ISSUE TITLE
パスワードがレスポンスに含まれてしまう

### ISSUE THREAD

**Issue by tkomatsu** [RIFT-tokyo/transcendence-api#25]
現時点の実装だと、interceptorがUser entityに対して実行される。
しかし、apiのレスポンスはResponseUserを返しており、ResponseUserとして返す場合はinterceptorが働かなくなる。
ResponseUserが返るときにinterceptorが働いてパスワードが除外されるようにする実装に変更する。

**Comment by nafuka11** [comment]
password以外に、intra_idの削除も本Issueで対応します。
